### ISSUE TITLE
[QUESTION] Push notification

### ISSUE THREAD

**Issue by xchwarze** [davidtito1992/react-native-zendesk-ichat#4]
How do I use Push notification?
I tried to do it but it seems that I am missing something

**Comment by davidtito1992** [comment]
This package does not yet implement push notification automatically, did you follow the instructions in the documentation?
https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/push_notifications
https://developer.zendesk.com/embeddables/docs/android-chat-sdk/push_notifications

**Comment by 1awaleed** [comment]
Hello @davidtito1992 
I am having a cumbersome issue using this package with FCM push notifications. 
When a push notification launches the iOS app from a quit state it always crashes the app.

I followed zendesk documentation that is described above like so:

```objC
- (void) application:(UIApplication*)app didRegisterForRemoteNotificationsWithDeviceToken:(NSData*)tokenData {
    [ZDCChat setPushToken:tokenData];
}

- (void) application:(UIApplication*)application didReceiveRemoteNotification:(NSDictionary*)userInfo {
    [ZDCChat didReceiveRemoteNotification:userInfo];
}

```

Here is also a stack trace of the native crash:
 
<img width="386" alt="Screen Shot 2021-01-16 at 5 24 31 AM 2" src="https://user-images.githubusercontent.com/50215696/104799038-6db20a80-57d4-11eb-8d41-53435a32c0bc.png">
